### ISSUE TITLE
Host in a crowd-sourced translation platform

### ISSUE THREAD

**Issue by Madis0** [modrinth/translations#3]
Please host this somewhere for easier collaboration and updates.

I suggest
* [Crowdin](https://crowdin.com/page/open-source-project-setup-request) (free for FOSS and has the best UX and most users IMO)
* [Transifex](https://docs.transifex.com/projects/open-source-project) (also free for FOSS)
* [Weblate](https://weblate.org/en/) (self-host)

**Comment by wafflecoffee** [comment]
Re: Crowdin:
> You do not have any commercial products related to the open-source project you are requesting a license for.

This is a dealbreaker, because technically Modrinth is still a commercial product.
It looks like Transifex would have similar restrictions.

**Comment by Madis0** [comment]
Hmm okay. It is also possible to host Crowdin somehow, I've seen custom domains at least for some projects. But otherwise if license fees are unacceptable, then yeah - Weblate.

**Comment by Brawaru** [comment]
I remember contacting Crowdin and they said that having ads would be alright, I guess it's alright as long as you don't sell anything (in which case you'll be able to pay for licence). You might want [to contact](https://crowdin.com/contacts) their support (they're very responsible and polite people) to see if that actually will be a deal-breaker.

**Comment by wafflecoffee** [comment]
I guess it's mostly about the idea that we leave open the option of selling something in the future (Modrinth+ or something to support modders directly, if we ever want to do that).

**Comment by Brawaru** [comment]
I mean, it can be revised in the future when that happens: by then either Crowdin plans will be affordable to pay for, or switch will have to be made and maybe Weblate will improve and not be as horrible to use. Just have to keep that in mind and not hardwire Crowdin into the code or CI (which is relatively easy to do), that is if they grant open source plan in the first place, of course, which is why it worth contacting support to make sure they're alright with that order of things.

**Comment by venashial** [comment]
I contacted Crowdin, if that doesn't work out we'll have to try something else.
